import React from "react";
import { Flex, Button, VStack, Stack, Box, Image, Heading } from "@chakra-ui/react";
import {
  BrowserRouter as Router,
  Link,
  Switch,
  Route,
  useLocation,
} from "react-router-dom";
import { useTransition, animated } from "react-spring";
import BookingsByPassengerTypeReport from "../../Containers/Reports/BookingsByPassengerTypeReport";
import PassengersForDestinationReport from "../../Containers/Reports/PassengersForDestinationReport";
import PassengersInFlightReport from "../../Containers/Reports/PassengersInFlightReport";
import RevenueReport from "../../Containers/Reports/RevenueReport";
import FlightDetailsReport from "../../Containers/Reports/FlightDetailsReport";
import ManagementHeader from "../../Containers/Management/ManagementHeader";
import Footer from "../../Components/Footer/Footer";

const Dashboard = () => {
  return (
    <Router>
      <div>
        <ManagementHeader />
        <Content />
        <Footer />
      </div>
    </Router>
  );
};

const Home = () => {
  return (
    <div>
      <Flex
        align="center"
        justify={{ base: "center", md: "space-around", xl: "space-between" }}
        direction={{ base: "column-reverse", md: "row" }}
        wrap="no-wrap"
        minH="70vh"
        px={8}
        mb={16}
      >
        <Stack
          spacing={4}
          w={{ base: "80%", md: "40%" }}
          align={["center", "center", "flex-start", "flex-start"]}
        >
          <Heading
          as="h1"
          size="xl"
          fontWeight="bold"
          color="primary.800"
          textAlign={["center", "center", "left", "left"]}
        >
          Reports
        </Heading>
        <Buttons />
        </Stack>
        <Box w={{ base: "80%", sm: "60%", md: "50%" }} mb={{ base: 12, md: 0 }}>
          <Image
            src="/images/reports.jpg"
            size="100%"
            rounded="1rem"
            shadow="2xl"
          />
        </Box>
      </Flex>
    </div>
  )
}

const Buttons = () => {
  return (
    <VStack align="left" justify="center">
      <Link to={"/BookingsByPassengerTypeReport"}>
        <Button variant="link" borderRadius="8px" py="4" px="4" lineHeight="1" size="lg" colorScheme="purple">
          Number of Bookings by each Passenger Type
        </Button>
      </Link>
      <Link to={"/PassengersForDestinationReport"}>
        <Button variant="link" borderRadius="8px" py="4" px="4" lineHeight="1" size="lg" colorScheme="purple">
          Number of Passengers Travelling to a Given Destination
        </Button>
      </Link>
      <Link to={"/PassengersInFlightReport"}>
        <Button variant="link" borderRadius="8px" py="4" px="4" lineHeight="1" size="lg" colorScheme="purple">
          Passengers Travelling in a Flight
        </Button>
      </Link>
      <Link to={"/RevenueReport"}>
        <Button variant="link" borderRadius="8px" py="4" px="4" lineHeight="1" size="lg" colorScheme="purple">
          Total Revenue Generated by each Aircraft Type
        </Button>
      </Link>
      <Link to={"/FlightDetailsReport"}>
        <Button variant="link" borderRadius="8px" py="4" px="4" lineHeight="1" size="lg" colorScheme="purple">
          All Past Flights, States, Passenger Counts Data
        </Button>
      </Link>
    </VStack>
  );
};

const Content = () => {
  const location = useLocation();
  const transitions = useTransition(location, (location) => location.pathname, {
    from: { position: "absolute", opacity: 0 },
    enter: { opacity: 1 },
    leave: { opacity: 0 },
  });

  return transitions.map(({ item, props, key }) => (
    <animated.div key={key} style={props}>
      <Flex mt={5} flexDirection="column" minWidth="100vw">
        <Flex justifyContent="center" minWidth="80%">
          <Switch location={item}>
            <Route path="/BookingsByPassengerTypeReport">
              <BookingsByPassengerTypeReport />
            </Route>
            <Route path="/PassengersForDestinationReport">
              <PassengersForDestinationReport />
            </Route>
            <Route path="/PassengersInFlightReport">
              <PassengersInFlightReport />
            </Route>
            <Route path="/RevenueReport">
              <RevenueReport />
            </Route>
            <Route path="/FlightDetailsReport">
              <FlightDetailsReport />
            </Route>
            <Route path="/">
              <Home />
            </Route>
          </Switch>
        </Flex>
      </Flex>
    </animated.div>
  ));
};

export default Dashboard;
